Repository RocketChat/Rocket.Chat.Kotlin.SDK, pull requests merged in 2018-04, with the labels that each got.

#116 [New] Add favorite field in ChatRoom and Subscription object
  core/src/main/kotlin/chat/rocket/core/internal/model/Subscription.kt
  core/src/main/kotlin/chat/rocket/core/model/ChatRoom.kt
Labels: feature

#118 [NEW] Add OwnBasicInformation for the user.
  common/src/main/kotlin/chat/rocket/common/model/User.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/OwnBasicInformationPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/UserTest.kt
Labels: feature, rest

#96 [NEW] Rest call to create new channel
  core/src/main/kotlin/chat/rocket/core/internal/model/CreateNewChannelPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Channel.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChannelTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
Labels: feature, rest

#121 [NEW] Add call to chat.sendMessage endpoint
  core/src/main/kotlin/chat/rocket/core/internal/model/PostMessagePayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/SendMessagePayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Messages.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/MessagesTest.kt
Labels: rest

#123 [NEW] Add real-time api to get user data changes.
  core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/Messages.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/Socket.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/Subscriptions.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/User.kt
  core/src/main/kotlin/chat/rocket/core/model/Myself.kt
  sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Labels: feature, websocket

#127 [PROJECT] Improves core module packages.
  common/src/main/kotlin/chat/rocket/common/model/BaseUser.kt
  core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/SocketToken.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/ChatRoom.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/Messages.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/Subscriptions.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/User.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/message/Connect.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/message/MethodCall.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/message/Subscription.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Login.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Subscription.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/message/collection/StreamNotifyUser.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/message/collection/StreamRoomMessages.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/message/collection/Users.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/message/model/SocketMessage.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/model/ReconnectionStrategy.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/model/SocketToken.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/model/State.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/model/StreamMessage.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Messages.kt
  sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Labels: project

#132 [NEW] Add ColorAttachment (need a better name)
  core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
  core/src/main/kotlin/chat/rocket/core/model/attachment/ColorAttachment.kt
  core/src/main/kotlin/chat/rocket/core/model/attachment/MessageAttachment.kt
Labels: feature

#134 [NEW] Add ColorAttachment (need a better name)
  core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
  core/src/main/kotlin/chat/rocket/core/model/attachment/ColorAttachment.kt
  core/src/main/kotlin/chat/rocket/core/model/attachment/MessageAttachment.kt
Labels: feature

#138 [FIX] Fix crash on attachment fields when it has an array with a null value
  core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
  core/src/main/kotlin/chat/rocket/core/model/attachment/Field.kt
Labels: bug

#141 [FIX] settings.oauth payload.
  common/src/main/kotlin/chat/rocket/common/model/SettingsOauth.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
Labels: bug

#140 [NEW] Add ForgotPassword.
  core/src/main/kotlin/chat/rocket/core/internal/model/ForgotPasswordPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/SignUpPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/LoginTest.kt
Labels: feature, rest

#104 [NEW] Support for querying users based on regex.
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
Labels: feature, rest

#150 [FIX] Make {audio,video}{Type,Size} nullable on AttachmentAdapter
  core/src/main/kotlin/chat/rocket/core/internal/AttachmentAdapter.kt
Labels: bug
