Repository RocketChat/Rocket.Chat.Kotlin.SDK, pull requests merged in 2018-06, with the labels that each got.

#175 [FIX] Sets uploadedAt as possible null.
  core/src/main/kotlin/chat/rocket/core/model/attachment/GenericAttachment.kt
Labels: bug

#176 [NEW] Add unread property to Message object
  core/src/main/kotlin/chat/rocket/core/model/Message.kt
Labels: feature

#178 [PROJECT] Removes the searchUser function.
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
Labels: project

#114 [NEW] Added Room Settings Functions
  core/src/main/kotlin/chat/rocket/core/internal/model/ChatRoomPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/RoomIdPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/Subscription.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/main/kotlin/chat/rocket/core/model/ChatRoom.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
Labels: feature, rest

#185 [NEW] Mention list
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/Constants.kt
Labels: feature, rest

#188 [NEW] Favorite/unfavorite chatroom
  core/src/main/kotlin/chat/rocket/core/internal/model/ChatRoomPayload.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
Labels: feature, rest

#190 [NEW] User agent
  core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/socket/Socket.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Channel.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Commands.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Login.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Logout.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Message.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Permissions.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Push.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/RestClient.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Spotlight.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt
  core/src/test/kotlin/chat/rocket/core/internal/ReactionsAdapterTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/RoomListAdapterTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChannelTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/CommandsTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/LoginTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/LogoutTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/MessagesTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/PermissionsTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/RolesTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/SpotlightTest.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/UserTest.kt
  sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Labels: improvement
