Repository RocketChat/Rocket.Chat.Kotlin.SDK, pull requests merged in 2018-05, with the labels that each got.

#149 [NEW] Add send typing status.
  core/src/main/kotlin/chat/rocket/core/internal/realtime/ChatRoom.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/message/MethodCall.kt
  sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Labels: feature, websocket

#158 [NEW] Add Subscription role change message types
  core/src/main/kotlin/chat/rocket/core/model/Message.kt
Labels: improvement

#159 [NEW] Detect redirections on /api/info
  common/src/main/kotlin/chat/rocket/common/model/ServerInfo.kt
  core/src/main/kotlin/chat/rocket/core/internal/model/ServerInfoResponse.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/RestClient.kt
  core/src/main/kotlin/chat/rocket/core/internal/rest/Server.kt
Labels: bug, enhancement, feature

#162 [IMPROVEMENT] Add documentation
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/test/kotlin/chat/rocket/core/internal/rest/ChatRoomTest.kt
Labels: docs, improvement

#165 [FIX] Fix null values on Settings Adapter
  core/src/main/kotlin/chat/rocket/core/internal/SettingsAdapter.kt
Labels: bug

#171 [NEW] Add chat room file list.
  core/src/main/kotlin/chat/rocket/core/internal/rest/ChatRoom.kt
  core/src/main/kotlin/chat/rocket/core/model/attachment/GenericAttachment.kt
  sample/src/main/kotlin/rocket/chat/kotlin/sample/Sample.kt
Labels: feature, rest

#174 [NEW] Implement createDirectMessage realtime method call
  core/src/main/kotlin/chat/rocket/core/internal/realtime/ChatRoom.kt
  core/src/main/kotlin/chat/rocket/core/internal/realtime/message/MethodCall.kt
Labels: feature
